<?php

namespace Nimbbl\Api\Common;

/**
 * Error codes used throughout the SDK
 * 
 * Centralized error codes to ensure consistency and make it easier to maintain.
 */
class ErrorCodes
{
    const SIGNATURE_VERIFICATION_FAILED = 'SIGNATURE_VERIFICATION_FAILED';
    const SIGNATURE_VERIFICATION_MISSING_PARAMS = 'SIGNATURE_VERIFICATION_MISSING_PARAMS';
    const SIGNATURE_VERIFICATION_ERROR = 'SIGNATURE_VERIFICATION_ERROR';
    const DESERIALIZATION_ERROR = 'DESERIALIZATION_ERROR';
    const AUTH_ERROR = 'AUTH_ERROR';
    const SERVER_ERROR = 'SERVER_ERROR';
    const INVALID_ACCESS_SECRET = 'INVALID_ACCESS_SECRET';
    const INVALID_HEX_STRING = 'INVALID_HEX_STRING';
    const DECRYPTION_ERROR = 'DECRYPTION_ERROR';
    const ENCRYPTION_ERROR = 'ENCRYPTION_ERROR';
    const PINCODE_REQUIRED = 'PINCODE_REQUIRED';
    const REFRESH_TOKEN_REQUIRED = 'REFRESH_TOKEN_REQUIRED';
    const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
    const IDENTIFIER_REQUIRED = 'IDENTIFIER_REQUIRED';
    const ACTION_REQUIRED = 'ACTION_REQUIRED';
    const INVALID_ACTION = 'INVALID_ACTION';
}
